---
#
#Use "§" as a color symbol
#Use "\n" to go to the next line
#The title of the menu
Title: "§lSellUI"

#Message when changing gamemode to creative
msg-Hand: "Sold"

#Message when changing gamemode to Survival
msg-All: "Sold"

#Message when changing gamemode to Adventure
msg-Inv: "Sold"

#Message when changing gamemode to spectator
msg-Shop: "Buy items"

#Message when player didn't have perm
msg-no-perm: "§cYou didn't have permission to use this command!"
#
...
